package com.z9tether.app

import android.Manifest
import android.app.Activity
import android.content.*
import android.os.*
import android.provider.MediaStore
import android.widget.*
import java.io.IOException
import java.net.Socket
import java.util.Base64
import kotlin.concurrent.thread

class MainActivity : Activity() {
    private lateinit var status:TextView; private lateinit var ip:TextView; private lateinit var count:TextView; private lateinit var latest:TextView; private lateinit var preview:ImageView; private lateinit var start:Button; private lateinit var testResult:TextView
    private var receiverOn=false
    private val events=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){if(i?.action!=FtpReceiverService.ACTION_EVENT)return;when(i.getStringExtra(FtpReceiverService.EXTRA_TYPE)){FtpReceiverService.TYPE_STARTED->setRunning(true);FtpReceiverService.TYPE_STOPPED->setRunning(false);FtpReceiverService.TYPE_IP->{ip.text="Phone IP: ${i.getStringExtra(FtpReceiverService.EXTRA_IP).orEmpty().ifBlank{"not detected"}}"};FtpReceiverService.TYPE_ERROR->{testResult.text="ERROR: ${i.getStringExtra(FtpReceiverService.EXTRA_MESSAGE)}"};FtpReceiverService.TYPE_RECEIVED->{val n=i.getIntExtra(FtpReceiverService.EXTRA_COUNT,0);count.text="$n photo${if(n==1)""else"s"} received";latest.text="Latest: ${i.getStringExtra(FtpReceiverService.EXTRA_NAME)?:"photo"}";testResult.text="✓ FTP upload received successfully";refreshLatest()}}}}
    override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);ip=findViewById(R.id.ip);count=findViewById(R.id.count);latest=findViewById(R.id.latest);preview=findViewById(R.id.preview);start=findViewById(R.id.start);testResult=findViewById(R.id.testResult);refreshIp();start.setOnClickListener{if(receiverOn)stopReceiver()else startReceiver()};findViewById<Button>(R.id.refresh).setOnClickListener{refreshIp();refreshLatest()};findViewById<Button>(R.id.simulate).setOnClickListener{simulateUpload()};if(Build.VERSION.SDK_INT>=33)requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),20);if(intent.getBooleanExtra("test_mode",false)){startReceiver();Handler(Looper.getMainLooper()).postDelayed({simulateUpload()},5000)}}
    override fun onStart(){super.onStart();registerReceiver(events,IntentFilter(FtpReceiverService.ACTION_EVENT),RECEIVER_NOT_EXPORTED)}
    override fun onStop(){unregisterReceiver(events);super.onStop()}
    private fun startReceiver(){val i=Intent(this,FtpReceiverService::class.java);if(Build.VERSION.SDK_INT>=26)startForegroundService(i)else startService(i);refreshIp()}
    private fun stopReceiver(){stopService(Intent(this,FtpReceiverService::class.java));setRunning(false)}
    private fun setRunning(on:Boolean){receiverOn=on;status.text=if(on)"● READY" else "● OFFLINE";status.setTextColor(if(on)0xFF39C56A.toInt()else 0xFF9AA0AA.toInt());start.text=if(on)"STOP RECEIVER" else "START RECEIVER"}
    private fun refreshIp(){ip.text="Phone IP: ${NetworkUtils.localIpv4(this)?:"not detected"}"}
    private fun simulateUpload(){testResult.text="Testing FTP…";thread(name = "sim-z9") {try{val s=Socket("127.0.0.1",FtpReceiverService.CONTROL_PORT);s.soTimeout=10000;val input=s.getInputStream().bufferedReader();val out=s.getOutputStream().bufferedWriter();fun cmd(x:String):String{out.write(x);out.write("\r\n");out.flush();return input.readLine()?:(throw IOException("FTP connection closed"))};val banner=input.readLine()?:throw IOException("FTP connection closed before banner");if(!banner.startsWith("220"))throw IOException("Bad FTP banner: $banner");if(!cmd("USER nikon").startsWith("331"))throw IOException("USER failed");if(!cmd("PASS z9tether").startsWith("230"))throw IOException("PASS failed");val pasv=cmd("PASV");val nums=Regex("\\(([^)]*)\\)").find(pasv)?.groupValues?.get(1)?.split(',')?:throw IOException("PASV parse failed");val p=nums.takeLast(2).let{it[0].toInt()*256+it[1].toInt()};val data=Socket("127.0.0.1",p);if(!cmd("STOR Z9_SIMULATED.JPG").startsWith("150"))throw IOException("STOR failed");data.getOutputStream().use{it.write(testJpeg())};data.close();val done=input.readLine()?:"";if(!done.startsWith("226"))throw IOException("Transfer failed: $done");cmd("QUIT");s.close();getSharedPreferences("test_results", MODE_PRIVATE).edit().putString("last_test","PASS").apply();runOnUiThread{testResult.text="✓ Simulated Z9 upload complete"}}catch(e:Exception){getSharedPreferences("test_results", MODE_PRIVATE).edit().putString("last_test","FAIL:${e.message}").apply();runOnUiThread{testResult.text="✗ Test failed: ${e.message}"}}}}
    private fun testJpeg():ByteArray=Base64.getDecoder().decode("/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////2wBDAf//////////////////////////////////////////////////////////////////////////////////////wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIQAxAAAAH/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAEFAqf/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AT//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAECAQE/AT//xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAY/Aqf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAE/IQ//2gAMAwEAAgADAAAAEP/EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQMBAT8Qf//EABQRAQAAAAAAAAAAAAAAAAAAABD/2gAIAQIBAT8Qf//EABQQAQAAAAAAAAAAAAAAAAAAABD/2gAIAQEAAT8Qf//Z")
    private fun refreshLatest(){try{val p=arrayOf(MediaStore.Images.Media._ID,MediaStore.Images.Media.DISPLAY_NAME,MediaStore.Images.Media.DATE_ADDED);contentResolver.query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,p,"${MediaStore.Images.Media.DISPLAY_NAME} LIKE ?",arrayOf("Z9_%"),"${MediaStore.Images.Media.DATE_ADDED} DESC")?.use{c->if(c.moveToFirst()){val id=c.getLong(c.getColumnIndexOrThrow(MediaStore.Images.Media._ID));preview.setImageURI(ContentUris.withAppendedId(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,id))}}}catch(_:Exception){}}
}
